# Generated by Django 3.0.6 on 2020-05-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, unique=True)),
                ('question', models.CharField(max_length=500)),
                ('islink', models.BooleanField(default=False)),
                ('ispic', models.BooleanField(default=False)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
    ]
