# Generated by Django 3.0.6 on 2020-05-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20200508_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='email',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
