# Generated by Django 3.0.6 on 2020-05-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_auto_20200509_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='choice',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
