# Generated by Django 3.0.6 on 2020-05-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_auto_20200509_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='email',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
