# Generated by Django 3.0.6 on 2020-05-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_auto_20200509_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='id',
        ),
        migrations.AlterField(
            model_name='movies',
            name='order',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
