# Generated by Django 3.0.6 on 2020-05-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_auto_20200509_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='link',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='link',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='link',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
