# Generated by Django 3.0.6 on 2020-05-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_auto_20200510_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='link',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='question',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='movies',
            name='link',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='question',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='series',
            name='link',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='question',
            field=models.CharField(max_length=5000),
        ),
    ]
