# Generated by Django 3.0.6 on 2020-05-11 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0010_auto_20200511_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['day', 'order']},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['day', 'order']},
        ),
    ]
