# Generated by Django 3.0.6 on 2020-05-11 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0011_auto_20200511_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={},
        ),
    ]
